### Get to say welcome!
GET http://localhost:3000

### Get all users
GET http://localhost:3000/users

### Get user by id
GET http://localhost:3000/users/id/664367e4b68c9c666ab35167

### Get user by email
GET http://localhost:3000/users/email/correo@test.com

### Login by email and password
POSt http://localhost:3000/login
Content-Type: application/json
Accept: application/json

{
    "email": "paquitorremolinos@jotmeil.com",
    "password": "warakazumba"
}

### Checking existing user
POST http://localhost:3000/users/existingEmail
Content-Type: application/json
Accept: application/json

{
    "email": "usuario1@example.com"
}

### New publication
POST http://localhost:3000/addNewPublication
Content-Type: application/json
Accept: application/json

{
    "location": {
        "latitude": 0,
        "longitude": 0
    },
    "title": "Bancos de madera de la Laguna",
    "description": "Un sitio muy tranquilo donde pararse a descansar del día a día",
    "author": 9283749238749823,
    "rates": [],
    "comments": []
}