### Get to say welcome!
GET http://localhost:3000

### Get all users
GET http://localhost:3000/users

### Get user by id
GET http://localhost:3000/users/id/664367e4b68c9c666ab35167

### Get user by email
GET http://localhost:3000/users/email/correo@test.com

### Get all users without password
GET http://localhost:3000/getAllUsers

### Get all locations
GET http://localhost:3000/getAllLocations

### Request a verification code
POST http://localhost:3000/verificationCode
Content-Type: application/json
Accept: application/json

{
    "email": "woodybarkingbrown@gmail.com"
}

### Verify email with code
POST http://localhost:3000/verifyCode
Content-Type: application/json
Accept: application/json

{
    "email": "woodybarkingbrown@gmail.com",
    "code": "1351"
}

### Add new rate
POST http://localhost:3000/addRate
Content-Type: application/json
Accept: application/json

{
    "publicationId": "665b666d192a8ab06cd98437",
    "author": "665b650c65642513fab7d483",
    "rate": 1
}

### Check friend by id
POST http://localhost:3000/checkFriendById
Content-Type: application/json
Accept: application/json

{
    "authId": "664fa7682cf06e67d4e300f7",
    "friendId": "6653114ab712bba1113071fb"
}

### Get publications by id
POST http://localhost:3000/getPublicationsById
Content-Type: application/json
Accept: application/json

{
    "authId": "664fa7682cf06e67d4e300f7"
}

### Get friends by id
POST http://localhost:3000/getFriendsById
Content-Type: application/json
Accept: application/json

{
    "authId": "664fa7682cf06e67d4e300f7"
}

### Follow a friend by id
PUT  http://localhost:3000/followUser
Content-Type: application/json
Accept: application/json

{
    "authId": "664fa7682cf06e67d4e300f7",
    "friendId": "6653114ab712bba1113071fb"
}

### Follow a friend by id
PUT  http://localhost:3000/unFollowUser
Content-Type: application/json
Accept: application/json

{
    "authId": "664fa7682cf06e67d4e300f7",
    "friendId": "6653114ab712bba1113071fb"
}

### Get comments by id
POST  http://localhost:3000/getCommentsById
Content-Type: application/json
Accept: application/json

{
    "publicationId": "664fa813cbd010cfa056b84f"
}

### Add new comment by id
PUT  http://localhost:3000/addNewComment
Content-Type: application/json
Accept: application/json

{
    "publicationId": "664fa813cbd010cfa056b84f",
    "authId": "6653114ab712bba1113071fb",
    "comment": "Otro comentario más"
}

### Login by email and password
POSt http://localhost:3000/login
Content-Type: application/json
Accept: application/json

{
    "email": "jcostosmolina@gmail.com",
    "password": "warakazumba"
}

### Checking existing user
POST http://localhost:3000/users/existingEmail
Content-Type: application/json
Accept: application/json

{
    "email": "usuario1@example.com"
}

### New publication
POST http://localhost:3000/addNewPublication
Content-Type: application/json
Accept: application/json

{
    "location": {
        "latitude": 0,
        "longitude": 0
    },
    "title": "Bancos de madera de la Laguna",
    "description": "Un sitio muy tranquilo donde pararse a descansar del día a día",
    "author": 9283749238749823,
    "rates": [],
    "comments": []
}